/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizz.buzz;

public class App {

    public static void main(String[] args) {


        for (long current = 1; current <= 100; ++current)
        {
            if (current %3 == 0 && current %5 ==0){
                System.out.println("FizzBuzz");
            }
            else if (current %5 == 0){
                System.out.println("Buzz");
            }
            else if(current %3 == 0) {
                System.out.println("Fizz");
            }
            else {
                System.out.println(current);
            }

        }
    }
}